# global:
#   scrape_interval: 4s

# scrape_configs:
#   - job_name: prometheus
#     static_configs:
#       - targets: ["192.168.1.12:8000"]

global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: []  # Initially empty; clients will be added automatically
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '$1'

